version: '3'
services:
    db: 
      image: postgres:10.5-alpine
      ports:
        - 5432
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - 'DB_ROOT_PASSWORD'
        - 'DB_USER'
        - 'DB_PASSWORD'
        - 'DB_DATABASE'
    flask:
        restart: always
        build: .
        volumes:
            - './:/app'
        ports:
            - "5000:5000"

volumes:
  postgres_data: