version: '3'
services:
    flask:
        restart: always
        build: .
        volumes:
            - './:/app'
        ports:
            - "5000:5000"
        depends_on:
            - dynamodb
        environment:
            - DYNAMODB_HOST=http://localhost:8000
    dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
            - "8000:8000"
        command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]